version: '3.8'

services:
    postgres:
        image: postgres:14.9-alpine
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=accounts
            - POSTGRES_PASSWORD=qwerty123
            - POSTGRES_USER=accounts
        volumes:
            - /var/lib/postgresql/data
            - ./dev/sql:/docker-entrypoint-initdb.d
