#!/bin/bash

cd "$( dirname "${BASH_SOURCE[0]}" )"

export PORT="3002"
export PGUSER="chaos"
export PGPASSWORD="qwerty123"
export PGHOST="localhost"
export PGPORT="5433"
export PGDATABASE="chaos"
export PGSSLMODE="disable"

# If this fails, you may need to install global packages using:
#  - `npm i -g concurrently`
#  - `npm i -g wait-on`
#  - `npm i -g nodemon`
concurrently -k -c auto -n DB,SERVER "docker compose -f ../../compose.dev.yml up --build" "wait-on tcp:5433 && nodemon --ext go --watch ../../**/*.* --exec go run ../../"
